server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: fabrick_task2
  main:
    web-application-type: servlet

application:
  aviation-weather:
    api:
      base-url: https://aviationweather.gov/api/data

logging:
  level:
    com.example.fabrick_task2: DEBUG
    org.springframework.web.client: DEBUG
  pattern:
    level: "%5p [%spring.application.name]"